//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmorDBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArmorDBEntities : DbContext
    {
        public ArmorDBEntities()
            : base("name=ArmorDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Armor> Armors { get; set; }
        public virtual DbSet<SetBonus> SetBonuses { get; set; }
        public virtual DbSet<Set> Sets { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
    }
}
