//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmorDBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Armor
    {
        public long ArmorID { get; set; }
        public string Name { get; set; }
        public long Rarity { get; set; }
        public long Slot1 { get; set; }
        public long Slot2 { get; set; }
        public long Slot3 { get; set; }
        public long MinDef { get; set; }
        public long MaxDef { get; set; }
        public long FireRes { get; set; }
        public long WaterRes { get; set; }
        public long ThunderRes { get; set; }
        public long IceRes { get; set; }
        public long DragonRes { get; set; }
        public long Event { get; set; }
        public Nullable<long> SetID { get; set; }
        public Nullable<long> Skill1ID { get; set; }
        public Nullable<long> Skill1Count { get; set; }
        public Nullable<long> Skill2ID { get; set; }
        public Nullable<long> Skill2Count { get; set; }
        public string Type { get; set; }
    
        public virtual Skill Skill { get; set; }
        public virtual Skill Skill1 { get; set; }
        public virtual Set Set { get; set; }
    }
}
